# Generated by Django 5.1.6 on 2025-02-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='is_achieved',
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'point'), (1, 'streak'), (2, 'hidden')], default=0),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='required_date',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='required_money',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
