# Generated by Django 5.1.6 on 2025-02-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_handwritten',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
