# Generated by Django 5.1.5 on 2025-02-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeparticipant',
            name='last_ocr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='is_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='ocr_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_handwritten',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
