# Generated by Django 5.1.5 on 2025-02-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengeparticipant_last_ocr_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeparticipant',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
