# Generated by Django 5.1.5 on 2025-02-12 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('challenge_invite', '챌린지 초대'), ('challenge_end', '챌린지 마감'), ('expense_reminder', '인증 재촉'), ('new_follower', '팔로우')], max_length=20)),
                ('reference_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notification',
                'indexes': [models.Index(fields=['user', '-created_at'], name='Notificatio_user_id_415290_idx'), models.Index(fields=['user', 'is_read'], name='Notificatio_user_id_7b231f_idx')],
            },
        ),
    ]
