# Generated by Django 5.1.5 on 2025-02-14 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.PositiveSmallIntegerField(choices=[(1, '학생'), (2, '대학(원)생'), (3, '취업준비생'), (4, '직장인'), (5, '주부'), (6, '프리랜서')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='굴비', error_messages={'unique': '이미 존재하는 닉네임입니다.'}, max_length=100, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userchallengecategory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
